/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BBucketIdSplatRouteImport } from './routes/b.$bucketId.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BBucketIdSplatRoute = BBucketIdSplatRouteImport.update({
  id: '/b/$bucketId/$',
  path: '/b/$bucketId/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/b/$bucketId/$': typeof BBucketIdSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/b/$bucketId/$': typeof BBucketIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/b/$bucketId/$': typeof BBucketIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/b/$bucketId/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/b/$bucketId/$'
  id: '__root__' | '/' | '/b/$bucketId/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BBucketIdSplatRoute: typeof BBucketIdSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$bucketId/$': {
      id: '/b/$bucketId/$'
      path: '/b/$bucketId/$'
      fullPath: '/b/$bucketId/$'
      preLoaderRoute: typeof BBucketIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BBucketIdSplatRoute: BBucketIdSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
